name: Publish

on:
  push:
    branches:
      - main
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
    tags:
      - 'v*'
  workflow_dispatch:

jobs:

  release:
    name: Publish
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ^1.19

      - name: Install gox
        run: go install github.com/mitchellh/gox@latest

      - name: Compile code
        run: make cross-compile

      - name: Get release version
        id: get_version
        run: |
          version=""
          if [ "${GITHUB_REF}" == "refs/heads/main" ]; then
            version="nightly"
          else
            version="$(make version)"
          fi
          echo "Version: ${version}"
          echo "::set-output name=version::${version}"

      - name: Publish release
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          automatic_release_tag: ${{ steps.get_version.outputs.version }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: ${{ github.ref == 'refs/heads/main' }}
          title: ${{ steps.get_version.outputs.version }}
          files: |
            build/plasmid-*
